modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory
issueTrackerURL="https://github.com/ToMe25/ToMeSetup/issues"
[[mods]] #mandatory
    modId="tomesetup" #mandatory
    version="${version}" #mandatory file.jarVersion
    displayName="ToMe Setup" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/tomesetup"
    logoFile="ToMeSetupLogo.png"
    credits="..."
    authors="ToMe25"
    description='''ToMe25(0)'s Setup Mod.'''
[[dependencies.tomesetup]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tomesetup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.14.4]"
    ordering="NONE"
    side="BOTH"
